"""LLM chat message models.

Defines provider-independent representation of chat messages and message roles.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field


class MessageRole(StrEnum):
    """Roles a message author can take in a chat conversation.

    Members:
        SYSTEM: Instructions setting assistant behaviour and system prompts.
        USER: Prompts and inputs provided by the human or external system.
        ASSISTANT: Responses generated by the AI model.
        TOOL: Output returned from executed tools/functions.
    """

    SYSTEM = "system"
    USER = "user"
    ASSISTANT = "assistant"
    TOOL = "tool"


class ChatMessage(BaseModel):
    """Provider-independent representation of a single chat message.

    Attributes:
        role: Author role (system, user, assistant, tool).
        content: Text content of the message.
        name: Optional author name or identifier.
        tool_call_id: Optional ID referencing a tool call if role is 'tool'.
        metadata: Optional dictionary of additional provider or application context.
    """

    role: MessageRole | str = Field(
        ...,
        description="Author role in the conversation.",
    )
    content: str = Field(
        ...,
        description="Text content of the message.",
    )
    name: str | None = Field(
        default=None,
        description="Optional author name identifier.",
    )
    tool_call_id: str | None = Field(
        default=None,
        description="Optional tool call reference ID.",
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Provider-independent message metadata.",
    )
