"""Research execution ORM model for persisting ResearchAgent execution history."""

from __future__ import annotations

import uuid
from typing import Any

from sqlalchemy import JSON, Float, Index, String, Text, Uuid
from sqlalchemy.orm import Mapped, mapped_column

from app.infrastructure.database.models.base_model import BaseModel


class ResearchExecutionModel(BaseModel):
    """ORM entity storing ResearchAgent execution history.

    Attributes:
        user_id: Foreign/owner UUID of the user who initiated research.
        prompt: User research query or prompt string.
        response: Synthesized answer text generated by LLM Gateway.
        provider: Provider identifier (e.g. 'omniroute').
        model: Model identifier (e.g. 'best-free').
        latency_ms: Latency duration in milliseconds.
        usage: Token usage dictionary (prompt_tokens, completion_tokens, total_tokens).
    """

    __tablename__ = "research_executions"

    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        nullable=False,
        index=True,
    )
    prompt: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    response: Mapped[str] = mapped_column(
        Text,
        nullable=False,
    )
    provider: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="omniroute",
    )
    model: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        default="best-free",
    )
    latency_ms: Mapped[float] = mapped_column(
        Float,
        nullable=False,
        default=0.0,
    )
    usage: Mapped[dict[str, Any]] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
    )

    __table_args__ = (
        Index("ix_research_executions_user_created", "user_id", "created_at"),
    )
